version: '3'
services:
  app:
    build: .
    ports:
      - "4600:4200"
      - "9105:9005"
    volumes:
    - .:/app
    - /app/node_modules   # Agrega esta línea para crear un volumen separado para node_modules
